name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Access secrets and use them
        env:
          API_KEY: ${{ secrets.API_KEY }} # Accessing the secret
        run: |
          echo "My secret API key is $API_KEY"
          # Use $API_KEY in your commands or scripts
          # For example:
          # Replace the following with your actual build commands
          npm install
          npm run build
          # Replace the following with your actual deployment commands using $API_KEY
          echo "Deploying using API key: $API_KEY"
          # Your deployment commands here
