jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use the secret in your workflow
        env:
          API_KEY: ${{ secrets.API_KEY }} # Accessing the secret
        run: |
          echo "My secret API key is $API_KEY"
          # Use $API_KEY in your commands or scripts
          # Run your build or deploy commands here
